### ISSUE TITLE
How fast should we ping?

### ISSUE THREAD

**Issue by richb-hanover** [lynxthecat/CAKE-autorate#18]
_I want to split #17 - This is a new and important topic that should be considered separately from the CPU usage discussion. I wrote:_

I'd like to look back to a comment from [@Marctraider](https://github.com/lynxthecat/sqm-autorate/issues/17#issuecomment-1061021856)

> Not entirely related to this, but assuming cpu usage is fixed; Is it possible to have even lower than .1 (100ms) of ping intervals with regular ping? Or is that the limit?

As we continue our research, I hope we explore the other direction: _how slowly can we send those pings while still maintaining good latency and speed control?_ Finding a good lower limit to the ping rate would have these advantages:

- It obviously uses less CPU
- It avoids the "tragedy of the commons", where one person pinging those well-known hosts works really for them; ten million CAKE-autorate people (generating 100 million pings/second) would be a tragedy.

Do we have any information about how rapidly/how much LTE or Cable Modem speeds vary in real life? Maybe we could collect it ourselves...

We could collect long-term data (over the course of hours? maybe even days?) that record how often the CAKE-autorate algorithm needs to adjust the parameters, and the effect those changes made on latency (or the effect on latency, had those changes not been made...)

---
There were two thoughtful replies, which the authors are invited to append to this discussion so they don't get buried in the CPU usage discussion: 

@marctraider wrote https://github.com/lynxthecat/sqm-autorate/issues/17#issuecomment-1061313873

@moeller0 wrote https://github.com/lynxthecat/sqm-autorate/issues/17#issuecomment-1061596391

**Comment by moeller0** [comment]
Let me summarize, I believe there are two issues at play here:
1) Ping-rate per reflector: each individual reflector will only give useful delay responses up to a certain aggregate rate (that is true no matter whether we use ICM echo requests, ICMP timestamps, or NTP time requests), so as good citizens we should not overwehelm individual reflectors (and might consider even adding reflectors to the pool). By default ping uses 1Hz and non super-users can increase this up to 5Hz, so I expect most reflectors will be willing to tolerate rates in that range (as long as the aggregate of all concurrent users of the reflector do not cross the total rate limit).

2) Effective delay sampling rate in the control loop: here in the spirit to respond early to bufferbloat, we should strive to respond as early as sanely possible (so full busy looping/pooling probably is not okay).

I think we can achieve a high 2) without causing a high 1) by interleaving delay probes to multiple reflectors.

To be good netizens, we need to monitor the responses and back-off/switch to different reflectors if we get signs of overload/throttling.

**Comment by lynxthecat** [comment]
Hmm, I take the point, but the baseline I had in mind is the compromise value you would otherwise set CAKE to absent adaptive rate control:

![image](https://user-images.githubusercontent.com/10721999/157274517-d6d3e352-91f6-4927-9f3d-09489f361792.png)

Is it a safe harbour that should work 95% of the time (save in the green region). In this state, there should almost never be bufferbloat.

**Comment by lynxthecat** [comment]
Hehe true. Well it's not quite the hard minimum. It's the baseline which is the compromise. The baseline is like 95% of time actual rate is higher than baseline. The minimum is like 100% of the time the actual rate is higher than the minimum. I did wonder about in the sleep mode setting the CAKE bandwidth to the minimum.

**Comment by moeller0** [comment]
I think without delay measurements it really should go back to the hard minimum...

**Comment by lynxthecat** [comment]
OK thanks. So either maintain base rate + reduced frequency pings, or back to hard minimum + no pings. I'm guessing the former is probably best. Any thoughts?

**Comment by moeller0** [comment]
Both sound okay....

**Comment by lynxthecat** [comment]
OK I implemented switch to hard minimum on sleep now.

**Comment by lynxthecat** [comment]
@moeller0 I have implemented having separate ping streams write to a common fifo. It seems to work well. 

Each pinger writes out:

`echo $timestamp $reflector $seq $rtt_baseline $rtt $rtt_delta > /tmp/CAKE-autorate/ping_fifo`

https://github.com/lynxthecat/CAKE-autorate/blob/6069321f5cbeaf577e42b42a6768c1335fefeb3c/CAKE-autorate.sh#L150

And read in here:

`while read -r timestamp reflector seq rtt_baseline rtt rtt_delta`

https://github.com/lynxthecat/CAKE-autorate/blob/6069321f5cbeaf577e42b42a6768c1335fefeb3c/CAKE-autorate.sh#L222

**Comment by moeller0** [comment]
Looks great, but please consider:

timestamp reflector seq ul_delay_baseline ul_delay ul_delay_delta dl_delay_baseline dl_delay dl_delay_delta

and just instantiate both with RTT for ICMP echo data that way the main code can be made to control dl and ul independently if true OWD data is available and still does the right thing for RTTs.

**Comment by moeller0** [comment]
BTW, using a FIFO here seems clever and the correct data structure,.

To check against partial writes you could write

timestamp reflector seq ul_delay_baseline ul_delay ul_delay_delta dl_delay_baseline dl_delay dl_delay_delta timestamp

if leading and trailing timestamp differs the record is corrupted and should be ignored....

**Comment by lynxthecat** [comment]
@Marctraider any chance you could test the new code in main for performance and CPU use? Please keep your old code if you actually use this regularly just incase the new code performs less well.

**Comment by Marctraider** [comment]
> 6069321

Yes i will soon test the new script, and definitely keep the old one as backup (been using that primarily for now) but further optimizations are always welcome.

**Comment by lynxthecat** [comment]
> My ultimate goal, without setting rtt threshold too low, it for script to react so fast that a spike of 30 or bigger is almost impossible while abruptly disconnecting my fastest line (while an iperf test is ongoing). Without impairing total bandwidth significantly.

That sounds like a nice goal to test for.

**Comment by lynxthecat** [comment]
Actually @Marctraider I forgot to mention - there was a significant breakthrough moment in which it dawned on a few of the contributors on the [OpenWrt thread](https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/108848) including myself and @moeller0 that every time bufferbloat is detected that is in of itself a capacity estimate of the line, and so the bandwidth at that point is set based on the actual bandwidth used, and not just the bandwidth of the previously set CAKE rate. 

Now, on bufferbloat, the rate is set according to:

`cur_rate=$(( ($load*$cur_rate*$rate_adjust_bufferbloat)/100000 ))`

https://github.com/lynxthecat/CAKE-autorate/blob/main/CAKE-autorate.sh#L53

That is, the new rate is set based on $rate_adjust_bufferbloat * the actual transfer rate ($load*$cur_rate) rather than being set based on only $rate_adjust_bufferbloat * the previous rate ($cur_rate). 

That way we actually use the line capacity estimate ($load*$cur_rate), as it were, to set the new CAKE bandwidth, and so the new set CAKE bandwidth should correctly undershoot from the higher actual line capacity.

For your use case:

`My ultimate goal, without setting rtt threshold too low, it for script to react so fast that a spike of 30 or bigger is almost impossible while abruptly disconnecting my fastest line (while an iperf test is ongoing). Without impairing total bandwidth significantly.`

I think this should handle this drop much better because now when you disconnect the fast line, the actual rate transferred ($load*$cur_rate) will drop, and by setting the new rate based on that, it should be much more appropriate. 

This will be set as soon as bufferbloat is detected, and you can see that by just enabling $output_monitoring_lines in the 'config.sh'.

**Comment by lynxthecat** [comment]
Something like that would really help create a standard test for these different tools. I would love a bash script that creates a battery of stress tests for different approaches. I am convinced mine is working very well now but this does seem pretty niche. I mean OpenWrt is already nice. CAKE is then even more niche. And CAKE-autorate is further niche still.
