### ISSUE TITLE
Breaks internet radio if min_dl_shaper_rate < radio_bitrate < high_load_thr * base_dl_shaper_rate

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/CAKE-autorate#21]
I have a really bad LTE connection now, with its download rate varying from 100 kbit/s to 10 Mbit/s, with 400 kbit/s being the typical. So I configured the rates as follows:

```
min_dl_shaper_rate=100 # minimum bandwidth for download
base_dl_shaper_rate=400 # steady state bandwidth for download
max_dl_shaper_rate=10000 # maximum bandwidth for download
```
... and the same for the other direction.

There is also an internet radio stream that I like, it's a 128 kbit/s AAC. Unfortunately, the settings above break this stream, if nothing else is going on. Here is what happens.

 * Both upload and download shapers start with 400 kbit/s, or otherwise decay to 400 kbit/s because of low load and no bufferbloat.
 * Then the "base rate is sustained" logic is triggered, and the script breaks out of the loop.
 * Both shapers are reset to 100 kbit/s, which is insufficient.

There is absolutely no reason to reset the bandwidth that low. Or, perhaps, there is no reason to break out of the loop.

A safe fix (which I still don't like, as it is mathematically inconsistent with "decaying" the rate up if it is below the base and the load is low) would be to reset the shapers' rates to the minimum only if the current load is less than high_load_thr * min_{dl,ul}_shaper_rate, not just when the base rate is sustained for a long time.

**Comment by lynxthecat** [comment]
Excellent post and I fully understand this situation. I am keen to resolve this for you. As a temporary fix how about you edit the code just to set the base rate on this breakout rather than minimum? 

I quite like the sound of your proposed solution. Another solution would be to maintain the base rate, but reduce the rate of the pings. 

@moeller0 any thoughts?

**Comment by patrakov** [comment]
@lynxthecat The "maintain the base rate, but reduce the rate of the pings" solution indeed looks nicer to me.

**Comment by patrakov** [comment]
On the second thought, if the utilization is lower than high_load_thr * base_dl_shaper_rate, I agree that there is, logically, no need to ping anything, because the result would not affect anything. So maybe the correct solution would be a combination of our proposals.

**Comment by lynxthecat** [comment]
I think I'm convinced. @moeller0 already suggested this. So we never breakout the loop, and on sustained base rate we kill off the pingers, restart them with reduced frequency (how much reduced I wonder?) And then keep the loop going. Upon rate change we kill off the pingers and restart them with the normal frequency.

**Comment by moeller0** [comment]
> * Both shapers are reset to 100 kbit/s, which is insufficient.
> 
> There is absolutely no reason to reset the bandwidth that low. Or, perhaps, there is no reason to break out of the loop.

Well, then don't configure `min_dl_shaper_rate=100` if 100 is too low?

The point is the minimum is not the absolute minimum you ever encounter on a link, but rather the rate at or below which you value throughput higher than low-latency. If you want 128Kbps streams than setting a minimum of 100 is a recipe for unhappiness.



> A safe fix (which I still don't like, as it is mathematically inconsistent with "decaying" the rate up if it is below the base and the load is low) would be to reset the shapers' rates to the minimum only if the current load is less than high_load_thr * min_{dl,ul}_shaper_rate, not just when the base rate is sustained for a long time.

Nice idea, but the problem is that "load" really is just an estimate... out of necessity we compare the actual throughput with what would be achievable at the set shaper rate in the same interval. But if the true bottleneck rate is much smaller than the shaper rate we get a low load estimate. So "load" is not a precise measurement of what is happening on the bottleneck (and if we would know exactly what rate is achievable at the bottleneck we would not need the autorate code, after all that is what we are trying to deduce).

But if the issue is that switching off the ping probes leads to bad results, don't do that then... reducing their rate seems fine if there is minimal load (like < 10% of the achievable rate at minimum shaper setting).

Or simply set a minimum rate you are really comfortable with?



> think I'm convinced. @moeller0 already suggested this. So we never breakout the loop, and on sustained base rate we kill off the pingers, restart them with reduced frequency (how much reduced I wonder?)

Naively, I would probably try to reduce the rate by a factor of 10, but if there is next to no traffic, maybe even every 10 seconds might be fine, but you need to sample load sufficiently fast that you notice increases in demand so you can increase the ping rate quickly.

BTW, for volume limited LTE reducing the ICMP packet size might actually be a good idea, I guess I have not understood why until now (on a flat rate link that seems a rather useless exercise, but on a fixed volume it makes considerably more sense).



> Or just keep the breakout and employ your test. I wonder if your test could replace the existing tests?

That will work in spite of low load being unreliable, since we are at minimum anyway, but personally  I prefer the thin out the ping rate approach better, as that will likely result in the link idling at the base rate instead of the minimum rate.

**Comment by patrakov** [comment]
> how much reduced I wonder?

My version:

 * If the utilization is below high_load_thr * min_dl_shaper_rate, stop them completely (because the numbers they return would not be used in any decisions anyway), and keep the shapers at the base rate (because that's the condition of breaking the loop).
 * If the utilization is between high_load_thr * min_dl_shaper_rate and high_load_thr * base_dl_shaper_rate, I don't really know what to do, but we do need to run the pingers, so that any bufferbloat is eventually detected. I would be OK with 5x or 10x reduced ping rates.
 * If the utilization is above high_load_thr * base_dl_shaper_rate, run the pingers as normal.

Another point (or, rather, opinion) is that base_dl_shaper_rate represents the assumed capacity of a connection that we know nothing about, and, for consistency between the "just started" and "resumed from an idle period" cases, should also be assumed to be the shaper rate that the user would be accepting to be corrected down, if necessary, after a burst of bufferbloat.

Maybe this is also the solution for the "reset to min" vs "reset to max" debate in the beginning of the https://forum.openwrt.org/t/cake-w-adaptive-bandwidth/108848 thread: reset to base, whatever it is.

---

> Well, then don't configure min_dl_shaper_rate=100 if 100 is too low?

> The point is the minimum is not the absolute minimum you ever encounter on a link, but rather the rate at or below which you value throughput higher than low-latency. If you want 128Kbps streams than setting a minimum of 100 is a recipe for unhappiness.

Well, the rate at which I value throughput rather than latency is still roughly 100 kbps. I fully accept that my link does not always support radio, but it should always support VoIP, which needs less than that. And for more convincing numbers, please imagine that the original report said that the radio stream is 256 kbps - the report would still be valid.

If you insist on the "don't do that" interpretation, perhaps it is a good idea to flag configurations with min_dl_shaper_rate < high_load_thr * base_dl_shaper_rate as invalid, because streams with bitrates between these values would be broken by the script, even if there is no bufferbloat?

**Comment by patrakov** [comment]
> Nice idea, but the problem is that "load" really is just an estimate... out of necessity we compare the actual throughput with what would be achievable at the set shaper rate in the same interval. But if the true bottleneck rate is much smaller than the shaper rate we get a low load estimate. So "load" is not a precise measurement of what is happening on the bottleneck (and if we would know exactly what rate is achievable at the bottleneck we would not need the autorate code, after all that is what we are trying to deduce).

I meant the actual throughput. My proposal was to not reset the shaper bandwidths to min, but keep them at base, and put the pingers to sleep only while the actual throughput is below high_load_thr * min_dl_shaper_rate.

**Comment by moeller0** [comment]
> * If the utilization is below high_load_thr * min_dl_shaper_rate, stop them completely (because the numbers they return would not be used in any decisions anyway), and keep the shapers at the base rate (because that's the condition of breaking the loop).

Well, the point is, either stay at the minimum rate and do not sample, or risk starting out with too high a shaper rate.
Not having looked closely, I assume that on noticeable traffic the ping train will resume anyway...



> Another point (or, rather, opinion) is that base_dl_shaper_rate represents the assumed capacity of a connection that we know nothing about, and, for consistency between the "just started" and "resumed from an idle period" cases, should also be assumed to be the shaper rate that the user would be accepting to be corrected down, if necessary, after a burst of bufferbloat.

That is an argument I can live with, after all, a user can set minimum rate = base rate... This clearly is a policy issue and hence without an a-priori right or wrong answer IMHO. I seem to recall, that was one of the options @lynxthecat's was pondering, so maybe that is the right thing to do here.

About adaptive ping rates, I would prefer not to overthink this, either stop or reduce the rate if `actual_thoughput_rate < min_rate * 0.25` for at least say 5 minutes, and start pining immediately once the load increases above the same threshold (0.25 is an example, I would turn this into a variable). The idea is whatever method to thin out the pings is, try to be sensitive to detect when to sample the RTT again. 



> Well, the rate at which I value throughput rather than latency is still roughly 100 kbps. I fully accept that my link does not always support radio, but it should always support VoIP, which needs less than that. And for more convincing numbers, please imagine that the original report said that the radio stream is 256 kbps - the report would still be valid.

To me it sounded like you expected your stream to always work, so that would set your minimum rate to 256 ion that case, but that was my misunderstanding, sorry... 
BTW, 100 Kbps is painfully low, because a full-MTU packet will take roughly:
(1538*8)/100 = 123.04 ms, so your pings can be delayed by that time (if a full MTU packet is in transfer when the ping packet arrives in the queue), making setting a useful threshold quite tricky.




> > Nice idea, but the problem is that "load" really is just an estimate... out of necessity we compare the actual throughput with what would be achievable at the set shaper rate in the same interval. But if the true bottleneck rate is much smaller than the shaper rate we get a low load estimate. So "load" is not a precise measurement of what is happening on the bottleneck (and if we would know exactly what rate is achievable at the bottleneck we would not need the autorate code, after all that is what we are trying to deduce).
> 
> I meant the actual throughput. My proposal was to not reset the shaper bandwidths to min, but keep them at base, and put the pingers to sleep only while the actual throughput is below high_load_thr * min_dl_shaper_rate.

I would, respectfully, agree to "persist" at the base rate, but be considerable more sensitive to start the pings again than `high_load_thr * min_dl_shaper_rate`, over a long sleep of the pings, the ping-baseline might have changed so getting a better estimate of that seems desirable. But then, I am not volume limited and hence would prefer to err on the side of more latency data than less.

**Comment by moeller0** [comment]
BTW, I agree with the analysis that the current mode is sub-optimal, but I wonder whether the drop-ping threshold might not be too low, after all there is still ongoing traffic, so maybe only engage the ping-saver IFF the actual throughput is  smaller than say min(50Kbps, 0.8 minimum_rate) (50 picked out of thin air, the idea is to allow a really small continuous background traffic with disabled pings, but start delay sampling again if there is more than "microwave background radiation)). But that is orthogonal to using base or minimum as set-point, where I agree that baseline seems a better fit to a user's expectation.

**Comment by moeller0** [comment]
> BTW, I agree with the analysis that the current mode is sub-optimal, but I wonder whether the drop-ping threshold might not be too high, after allin your streaming case there is still ongoing traffic, so maybe only engage the ping-saver IFF the actual throughput is smaller than say min(50Kbps, 0.2 minimum_rate) (50 picked out of thin air, the idea is to allow a really small continuous background traffic with disabled pings, but start delay sampling again if there is more than "microwave background radiation)). But that is orthogonal to using base or minimum as set-point, where I agree that baseline seems a better fit to a user's expectation, especially given that a user needs to select the baseline anyway.

**Comment by lynxthecat** [comment]
@patrakov and @moeller0 I agree to drop to base rate not min rate on the sleep mode if you both agree with this. 

Is the idea now to activate the sleep mode in the event that min(50Kbps, 0.2 minimum_rate) is sustained (and forget about the existing condition, which is to check for sustained base rate)?

**Comment by moeller0** [comment]
> @patrakov and @moeller0 I agree to drop to base rate not min rate on the sleep mode if you both agree with this. Please confirm.

I think we discussed this before and settled on the obviously latency conserving alternative, but @patrakov is right in that baseline_rate implies that this is the default value unless we have recent data that justifies changing that rate. The current behavior can be configured simply by setting min = base, so, I am all for this.



> Is the idea now to activate the sleep mode in the event that min(50Kbps, 0.2 minimum_rate) is sustained for X seconds (and forget about the existing condition, which is to check for sustained base rate for X seconds)? Actually how about just forgetting the 0.2 minimum rate and making it a user configurable value like 50Kbps?

I like that better actually... that value would need to be configurable anyway, so that seems decent. Again 50 was picked out of thin air, educated by the knowledge that on my link with my VoIP provider a single call will take ~100Kbps (actually a bit less) and I think a VoIP call already indicates a non-quiescient network. I would use a time criterion in addition, if only to avoid flipping between sampling/sleeping too fast, no?



> BTW 'X' is presently: sustained_base_rate_sleep_thr in 'config.sh'.

Big fan of putting the unit in the variable name so maybe:
sustained_base_rate_sleep_thr_sec or sustained_base_rate_sleep_cycles.



> Also it resumes extremely rapidly from the ping sleep state because it polls for load at the set ping interval. I could increase this polling frequency too if anyone sees a need.

I think polling load/thoughput at the normal nominal ping frequency is fine, I would not make this slower.

**Comment by patrakov** [comment]
Regarding the "drop to the base rate, not min rate" proposal, I agree that it would resolve this issue.

Regarding the rate at which to poll the load in the sleep mode, I agree with @moeller0 that it should be the same as the "normal" ping frequency.

Regarding the configurable value of the load at which to resume the pinger, well, not sure, because there is a well-defined load below which the result from the pinger doesn't matter, so setting the threshold at anything else would be self-inconsistent. As an example, in the situation when min_dl_shaper_rate = base_dl_shaper_rate, if the actual link load is less than high_load_thr * min_dl_shaper_rate, then there are only two possible outcomes from the pinger:

 * No bufferbloat, in which case the verdict is automatically "low_load", and there is no reason to do anything;
 * Bufferbloat, in which case there is still nothing to do, because the shaper is already at its minimum.

So with such a low load, we have no need to know whether there is bufferbloat, because we won't change the shaper settings anyway, and therefore we don't need the pinger. But with an infinitesimally higher load, there is a real decision: no bufferbloat then means "high_load" (and the corresponding increase of the shaper rate).

I guess that the correct formula for the threshold when the result from the pinger starts to matter (and thus the correct load to resume the pinger) is min(min_dl_shaper_rate, high_load_thr * base_dl_shaper_rate), but at this point (1am here) I can't really think about proofs.

**Comment by moeller0** [comment]
My point is we also need RTTs/OWDs to maintaim a robust bsseline estimate, so going blind is problematic, and when we start aampling sgain preferably when there is no congesgion so we do not learn a nufferbloated baseline.

**Comment by patrakov** [comment]
OK, then a user-settable threshold makes some sense, especially given the earlier comment "the minimum is not the absolute minimum you ever encounter on a link, but rather the rate at or below which you value throughput higher than low-latency".
