### ISSUE TITLE
Value too great for base

### ISSUE THREAD

**Issue by lrussell887** [lynxthecat/CAKE-autorate#30]
I had been running the script for about 19 days continuously when I noticed it had stopped working earlier today. I found the following in the `cake-autorate.log`:

```
/root/CAKE-autorate/CAKE-autorate.sh: line 136: (100*09: value too great for base (error token is "09")
Killing all background processes and cleaning up /tmp files.
rm: can't remove '/tmp/CAKE-autorate/pinger_0_fifo': No such file or directory
```

I'm not sure where the leading 0 comes from, but Bash seems to be treating it as octal leading to the error.

**Comment by lynxthecat** [comment]
Thanks a lot for this report. I am not sure where the leading 0 comes from either. It could possibly be because I have avoided use of flock for reads and writes by simply re-reading on a blank read. And so perhaps once in a blue moon this results in reading in a bad value? Or perhaps it is somewhere else in the code? 

Anyway, for now I have just forced the relevant calculation to interpret the relevant variable as decimal in this commit:

https://github.com/lynxthecat/CAKE-autorate/commit/76718345b4b5c699d7414ef0229642b8d9c2bf25

I think this should fix this issue?

**Comment by lrussell887** [comment]
Thank you for the fix, the script seems to be running normally with it. I'll let you know if I notice any more behavior like this.

**Comment by lrussell887** [comment]
I just noticed it had crashed again a few days ago after running for 25 days or so, it looks to be related.

```
/root/CAKE-autorate/CAKE-autorate.sh: line 135: (100*10#: invalid integer constant (error token is "10#")
Killing all background processes and cleaning up /tmp files.
rm: can't remove '/tmp/CAKE-autorate/pinger_0_fifo': No such file or directory
```

**Comment by lynxthecat** [comment]
I'm a bit stumped by this. 

`concurrent_read()
{
	# in the context of separate processes writing using > and reading form file
        # it seems costly calls to the external flock binary can be avoided
	# read either succeeds as expected or occassionally reads in bank value
	# so just test for blank value and re-read until not blank

	local -n value=$1
 	local path=$2
	read -r value < $path
	while [[ -z $value ]]; do
		sleep_us $concurrent_read_interval_us
		read -r value < $path; 
	done
}`

That shouldn't ever return an empty or unset string. 

So why are we getting this output error? 

@moeller0 any idea?

**Comment by lynxthecat** [comment]
One way forward might be to check that the value read is an integer rather than to check for unset or empty string. I should also check that the line that generated the error does not fail with zero.

**Comment by moeller0** [comment]
This looks a bit like avoiding flock (or alternative proper locking) might have occasional side effects, no?
Now, once in 25 days looks rare enough to just paper over this if possible, with the relative high RTT sampling any spurious or missing value is going to age out of the "window" relatively quickly (unless it will pull down the baseline considerable below its true value, as it will take a while before that climbs up again)...


Checking for a (positive?) integer (if possible in shell) seems like a valid exercise in caution anyways, and a way to create a proper autorate error/warning message (with timestamp the content of the read and an indication which function encountered the problem.)

**Comment by lynxthecat** [comment]
Thanks @moeller0 - will implement check and spit out a debug message on any misfires to help debug the issue. I want to understand what is going on exactly here.

**Comment by lynxthecat** [comment]
... actually I am too impatient to wait so for now have just revised the function to always check for positive integer and otherwise re-read in this commit: https://github.com/lynxthecat/CAKE-autorate/commit/b66e4e3b90c91ba10005a874598ef909563b3892

I will mark this issue as closed again, but if you see it still occur despite this fix then please comment again.
