### ISSUE TITLE
Cake-autorate reached rates differ from tc ones

### ISSUE THREAD

**Issue by the0** [lynxthecat/cake-autorate#311]
I'm currently using cake-autorate on my linux laptop and noticing that reached rates in cake-autorate log differ from byte counts reported by ts tool. As far as I know cake-autorate uses /sys/class/net/*/statistics for the data. So here is simple test showing counters difference for 10 seconds:
```
cat test.sh
#!/bin/bash

date +'%F %T'
tc_u0=$(tc -s qdisc show dev usb0 root | egrep Sent | awk '{ print $2 }')
tc_d0=$(tc -s qdisc show dev usb0-ifb root | egrep Sent | awk '{ print $2 }')
sys_u0=$(cat /sys/class/net/usb0/statistics/tx_bytes)
sys_d0=$(cat /sys/class/net/usb0/statistics/rx_bytes)
echo tc $tc_u0 $tc_d0
echo sys $sys_u0 $sys_d0
sleep 10
date +'%F %T'
tc_u1=$(tc -s qdisc show dev usb0 root | egrep Sent | awk '{ print $2 }')
tc_d1=$(tc -s qdisc show dev usb0-ifb root | egrep Sent | awk '{ print $2 }')
sys_u1=$(cat /sys/class/net/usb0/statistics/tx_bytes)
sys_d1=$(cat /sys/class/net/usb0/statistics/rx_bytes)
echo tc $tc_u1 $tc_d1
echo sys $sys_u1 $sys_d1
echo tc diff $((tc_u1 - tc_u0)) $((tc_d1 - tc_d0))
echo sys diff $((sys_u1 - sys_u0)) $((sys_d1 - sys_d0))
```
```
./test.sh 
2024-07-31 13:04:50
tc 51658292 3722312
sys 68192000 3247761
2024-07-31 13:05:00
tc 51781210 3731060
sys 68354544 3255361
tc diff 122918 8748
sys diff 162544 7600
```
Why do they differ so much, am I missing something?

**Comment by lynxthecat** [comment]
@moeller0 any thoughts? Don’t think this difference has anything to do with cake-autorate.

**Comment by moeller0** [comment]
Mmmh, interesting... I guess some differences are expected due to overheads and some due to accounting slack (yes measuring traffic volumes has some diagnostic value, but no, it likely does not need to be up to date every millisecond). But we are seeing 25% difference in one and -15% in the other directions that is a tad more than I would have expected...

I guess our challenge is that we want something that is cheap enough to query repeatedly and can live with some inaccuracy (I think we only take these rates as advisory anyway). So conceptually we could as well switch to use the tc output (assuming this is not computationally more costly)... but before doing that, we probably should try to understand which of the two is actually correct, and why does the sign of the delta switch between the true interface and the ifb.

I think we should start with collecting a bit more data with the example script (let's modify it to allow specifying the interface names as variables) and see how consistent these differences are and how they look if we actually push real data over the link.

**Comment by moeller0** [comment]
BTW, I agree that this is not something cake-autorate caused, but this still seems intreresting to resolve even if the outcome might be, yes sysfs values are imprecise, but still "good/cheap enough" for autorate's use-case.

**Comment by moeller0** [comment]
One reason to stick to sysfs is that this will still work when no cake instance is running... but I guess that is a edge use-case.
Sidenote: I think it is time to add a collector script for CPU load, so we collect the detailed CPU usage date (so it contained SIRQ) per CPU and maybe plot it with the rest of the data. That would allow to quickly check the relative CPU-cost of the two information sources. It would also help to diagnose situations where autorate starts to throttle due to running out of CPU (at which point cake accrues delays that could trigger rate throttling). This rate throttling is still a valid trigger for autorate as reducing the shaper rate will result in lower latency, but this is something that might be interesting for users to know, am I running against my link's capacity or am I running against my router's CPU limits, as both of these have different remedies/outlooks?

**Comment by lynxthecat** [comment]
Would you have an idea of which CPU statistic to track? There are a fair few.

**Comment by the0** [comment]
Please let me know if I can help somehow with diagnostics. By the way, I have also checked out iptables byte couters, bmon and iptraf-ng - they all show the same values as tc.

**Comment by the0** [comment]
> I guess our challenge is that we want something that is cheap enough to query repeatedly and can live with some inaccuracy (I think we only take these rates as advisory anyway). So conceptually we could as well switch to use the tc output (assuming this is not computationally more costly)... but before doing that, we probably should try to understand which of the two is actually correct, and why does the sign of the delta switch between the true interface and the ifb.

I'm also curious why "tc -s qdisc show dev usb0 ingress" stats differ from "tc -s qdisc show dev usb0-ifb root", is my ifb setup incorrect? I did that:

```
    tc qdisc del dev $iface root 2>/dev/null || true
    tc qdisc add dev $iface root handle 1: cake
    tc qdisc del dev $iface-ifb root 2>/dev/null || true
    tc qdisc add dev $iface-ifb root handle 1: cake ingress
    tc qdisc del dev $iface ingress 2>/dev/null || true
    tc qdisc add dev $iface handle ffff: ingress
    tc filter add dev $iface parent ffff: protocol ip u32 match u32 0 0 action mirred egress redirect dev $iface-ifb
```

**Comment by moeller0** [comment]
> Would you have an idea of which CPU statistic to track? There are a fair few.

Have a look at:
[https://www.idnt.net/en-US/kb/941772](https://www.idnt.net/en-US/kb/941772)
I would try to parse the cpuN lines from /proc/stat the trick is to make sure SIRQs are accounted as non-idle. This is not really all that tricky, but I guess will require some mildly expensive parsing at least in shell...

**Comment by rany2** [comment]
@the0 your TC rules are wrong, you're only matching IPv4 packets when mirroring to the ifb.

**Comment by moeller0** [comment]
So here is what we do in sqm-scripts:
```
tc filter add dev $IFACE parent ffff: protocol all prio 10 u32 match u32 0 0 flowid 1:1 action mirred egress redirect dev $DEV
```
as @rany2 pointed out (and I did not notice at all) IPv4/6 is a potential issue but `protocol all` will do the right thing here.

**Comment by the0** [comment]
> as @rany2 pointed out (and I did not notice at all) IPv4/6 is a potential issue but `protocol all` will do the right thing here.

Thanks, I changed by filter line to this:
```
tc filter add dev $iface parent ffff: protocol all prio 10 u32 match u32 0 0 action mirred egress redirect dev $iface-ifb
```
Also I have updated the test script:
```
cat test.sh 

#!/bin/bash

set -euo pipefail

test $# -eq 2 || exit 1

ul_if=$1
dl_if=$2

for i in $(seq 0 1); do

        date +'%F %T'

        tc2=$(tc -s qdisc show dev $dl_if root)
        tc2_dl_b[$i]=$(echo "$tc2" | egrep Sent | awk '{ print $2 }')
        tc2_dl_p[$i]=$(echo "$tc2" | egrep Sent | awk '{ print $4 }')
        tc1=$(tc -s qdisc show dev $ul_if)
        tc1_ul_b[$i]=$(echo "$tc1" | egrep Sent | head -1 | awk '{ print $2 }')
        tc1_ul_p[$i]=$(echo "$tc1" | egrep Sent | head -1 | awk '{ print $4 }')
        tc1_dl_b[$i]=$(echo "$tc1" | egrep Sent | tail -1 | awk '{ print $2 }')
        tc1_dl_p[$i]=$(echo "$tc1" | egrep Sent | tail -1 | awk '{ print $4 }')
        sys1_ul_b[$i]=$(cat /sys/class/net/$ul_if/statistics/tx_bytes)
        sys1_ul_p[$i]=$(cat /sys/class/net/$ul_if/statistics/tx_packets)
        sys1_dl_b[$i]=$(cat /sys/class/net/$ul_if/statistics/rx_bytes)
        sys1_dl_p[$i]=$(cat /sys/class/net/$ul_if/statistics/rx_packets)
        sys2_dl_b[$i]=$(cat /sys/class/net/$dl_if/statistics/tx_bytes)
        sys2_dl_p[$i]=$(cat /sys/class/net/$dl_if/statistics/tx_packets)

        echo tc1 ul$i ${tc1_ul_b[$i]} ${tc1_ul_p[$i]}
        echo tc1 dl$i ${tc1_dl_b[$i]} ${tc1_dl_p[$i]}
        echo tc2 dl$i ${tc2_dl_b[$i]} ${tc2_dl_p[$i]}
        echo sys1 ul$i ${sys1_ul_b[$i]} ${sys1_ul_p[$i]}
        echo sys1 dl$i ${sys1_dl_b[$i]} ${sys1_dl_p[$i]}
        echo sys2 dl$i ${sys2_dl_b[$i]} ${sys2_dl_p[$i]}

        sleep 10
        echo
done

echo tc1 ul diff $((tc1_ul_b[1] - tc1_ul_b[0])) $((tc1_ul_p[1] - tc1_ul_p[0]))
echo tc1 dl diff $((tc1_dl_b[1] - tc1_dl_b[0])) $((tc1_dl_p[1] - tc1_dl_p[0]))
echo tc2 dl diff $((tc2_dl_b[1] - tc2_dl_b[0])) $((tc2_dl_p[1] - tc2_dl_p[0]))
echo sys1 ul diff $((sys1_ul_b[1] - sys1_ul_b[0])) $((sys1_ul_p[1] - sys1_ul_p[0]))
echo sys1 dl diff $((sys1_dl_b[1] - sys1_dl_b[0])) $((sys1_dl_p[1] - sys1_dl_p[0]))
echo sys2 dl diff $((sys2_dl_b[1] - sys2_dl_b[0])) $((sys2_dl_p[1] - sys2_dl_p[0]))
```
Output is:
```
./test.sh usb0 usb0-ifb

2024-08-01 15:11:06
tc1 ul0 7935756 35322
tc1 dl0 1662414 20020
tc2 dl0 1942596 20019
sys1 ul0 9523058 35352
sys1 dl0 1664695 20042
sys2 dl0 1942694 20020

2024-08-01 15:11:16
tc1 ul1 13228382 39828
tc1 dl1 1669399 20103
tc2 dl1 1950841 20103
sys1 ul1 15017667 39866
sys1 dl1 1671764 20126
sys2 dl1 1950939 20104

tc1 ul diff 5292626 4506
tc1 dl diff 6985 83
tc2 dl diff 8245 84
sys1 ul diff 5494609 4514
sys1 dl diff 7069 84
sys2 dl diff 8245 84
```
And it still confuses me: I see diff in both byte counters tc1 dl vs tc2 dl and tc vs sys. If that matters, ipv6 disabled globally in kernel and iptables rules are empty.

**Comment by the0** [comment]
@moeller0 @rany2 any thoughts on this?

**Comment by lynxthecat** [comment]
Maybe try `matchall` rather than the u32 match (and manually inspect using tcpdump to verify all packets are copied over)?
