### ISSUE TITLE
The logic for replacing bad reflectors can hide bufferbloat

### ISSUE THREAD

**Issue by patrakov** [lynxthecat/cake-autorate#40]
If a reflector misbehaves, it is replaced. But what if this misbehavior (for all reflectors) is actually due to a total radio silence for a few seconds? Then, when the silence clears, the script will attempt to replace all reflectors, but this is the worst possible time: all packets buffered in the cell tower during the hiccup are now queued, and there is a lot of bufferbloat, while the script assumes that the initial reflector ping times represent the "normal" situation and can be trusted - which is not the case.

**Comment by moeller0** [comment]
Unless that is a common occurrence, I would opt for letting the default behavior, drop down to minimal rates during the drop out. Then after the connection re-starts we pick fresh reflectors with artificially high baselines but the baseline maintenance code aims to immediately accept lower values, so after the carnage cleared we will get rapidly improving baseline values again.
Since we just had an epoch of total radio silence we are in a degraded state anyway, and it really should not matter if we take a few seconds more to regain better bufferbloat mitigation, IMHO.
If these epochs happen a lot, there are more urgent problems to solve than autorate's baseline adaption code...

**Comment by lynxthecat** [comment]
I think this has been fixed with the new stall detection code.
